name: Ubuntu x86_64 | Testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  NVD_NO_NOTIFS: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update and download dependencies
      run: sudo apt update && sudo apt install libgtk-3-0 libgtk-3-dev
    - name: Fetch libnvdialog source
      run: git submodule update --init --recursive
    - name: Build crate
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
